bench: lint
	npm run benchmark > out.txt
	npm run benchmark > out.txt
	npm run benchmark > out.txt
	tail -n 23 out.txt > bench.txt
	rm out.txt
	npm run benchmark2 > bench2.txt
	node --prof prof-foo.js > /dev/null <--Here you need to add your prof-foo.js
	node --prof-process *.log > out.txt
	grep -A 5 "Summary" -R out.txt > tick-foo.txt <--Here you name the file like tick-foo.txt
	rm *.log && rm out.txt
	node --prof prof-bar.js > /dev/null <--Here you need to add your prof-bar.js
	node --prof-process *.log > out.txt
	grep -A 5 "Summary" -R out.txt > tick-bar.txt <--Here you name the file like tick-bar.txt
	rm *.log && rm out.txt && touch README.md && rm README.md
	echo '## Benchmark' >> README.md
	echo ' ' >> README.md
	echo '```' >> README.md
	cat bench.txt >> README.md
	echo '```' >> README.md
	echo ' ' >> README.md
	echo '## Benchmark 2' >> README.md
	echo ' ' >> README.md
	echo '```' >> README.md
	tail -n 4 bench2.txt >> README.md
	echo '```' >> README.md
	echo ' ' >> README.md
	echo '## Profile summary' >> README.md
	echo ' ' >> README.md
	echo 'Tick-foo' >> README.md <--Here you need to change
	echo '```' >> README.md
	cat tick-foo.txt >> README.md <--Here you need to change
	echo '```' >> README.md
	echo ' ' >> README.md
	echo 'Tick-bar' >> README.md <--Here you need to change
	echo '```' >> README.md
	cat tick-bar.txt >> README.md <--Here you need to change
	echo '```' >> README.md
	echo ' ' >> README.md
	rm *.txt
lint: node_modules
	npm run lint

clean:
	rm -rf node_modules

node_modules: init
	npm install

init: .
	cp ../package.json .
	cp ../.eslintrc.json .

.PHONY: init